- name: Create /etc/im dir
  file:
    path: /etc/im
    state: directory

- name: Create /var/log/im dir
  file:
    path: /var/log/im
    state: directory

- name: Set IM version
  set_fact:
    im_version: 'latest'
  when: im_version == ''

# workaround to fix ansible issue: https://github.com/ansible/ansible/issues/64016
- stat:
    path: /etc/im/im.cfg
  register: im_cfg

- name: Download IM cfg file
  get_url:
    url: https://raw.githubusercontent.com/grycap/im/master/etc/im.cfg
    dest: /etc/im/im.cfg
  when: not im_cfg.stat.exists

- name: Set OIDC issuers
  ini_file:
    dest: /etc/im/im.cfg
    section: im
    option: OIDC_ISSUERS
    value: "{{ im_oidc_issuers }}"

- name: Launch im container
  docker_container:
    name: im
    image: "grycap/im:{{im_version}}"
    state: started
    ports:
    - "8800:8800"
    - "8899:8899"
    exposed_ports:
    - 8899
    - 8800
    volumes:
    - "/etc/im:/data"
    - "/var/log/im:/var/log/im"
    - "/etc/im/im.cfg:/etc/im/im.cfg"
    env:
      IM_DATA_DB: "/data/inf.dat"