- name: Create /etc/im dir
  file: path=/etc/im state=directory

- name: Create /var/log/im dir
  file: path=/var/log/im state=directory

- name: Install dependencies for docker management
  pip: name=docker-py

- name: Launch im container
  docker:
    name: im
    image: "grycap/im:{{im_version}}"
    state: started
    ports:
    - "8800:8800"
    - "8899:8899"
    expose:
    - 8899
    - 8800
    volumes:
    - "/etc/im:/etc/im"
    - "/var/log/im:/var/log/im"