# Add a fast check to speed reconfiguration
- set_fact: IM_PATH=/usr/local/bin/im_service.py
  when: ansible_os_family == "Debian"

- set_fact: IM_PATH=/usr/bin/im_service.py
  when: ansible_os_family == "RedHat"

- stat: path={{IM_PATH}}
  register: im_installed

- block:
  - name: Include "{{ansible_os_family}}" tasks
    include: "{{ansible_os_family}}.yml"

  - name: Install last version of setuptools with Pip
    pip: name=setuptools extra_args="-I" state=latest
    ignore_errors: yes

  - name: Install backports.ssl_match_hostname
    pip: name=backports.ssl_match_hostname state=latest executable=pip
    
  - name: Install xmltodict
    pip: name=xmltodict state=latest executable=pip

  # Install IM using pip
  - name: Pip install IM
    pip: name=IM executable=pip
    when: im_version == "latest"

  # Install IM using pip but specific version
  - name: Pip install IM
    pip: name=IM version={{ im_version }} executable=pip
    when: im_version != "latest" and im_version != "devel"

  # Install IM getting devel branch from git
  - name: Install IM devel Version
    include: devel.yml
    when: im_version == "devel"

  # Use system package python-requests instead of pip version
  - pip: state=absent name=requests executable=pip
    name: Debian remove pip requests
    when: ansible_os_family == "Debian"

  - apt: name=python-requests
    name: Debian Install python-requests
    when: ansible_os_family == "Debian"

  - name: Disable IM REST API
    ini_file: dest=/etc/im/im.cfg section=im option=ACTIVATE_REST value=False

  - name: Set specific configuration in case of CentOS 6
    ini_file: dest=/etc/im/im.cfg section=im option=MAX_SIMULTANEOUS_LAUNCHES value=1
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

  - name: Set im script access rights
    file: path=/etc/init.d/im mode=0755

  - name: Start im service
    service: name=im state=started enabled=yes

    # This fixes a problem with the IM service in Centos 7
  - name: Kill and restart im service (Centos 7 only)
    shell: pgrep im | xargs kill && service im restart
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

  - name: Open port 8899
    iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=8899 action=insert
    ignore_errors: yes

  when: not im_installed.stat.exists
