- name: Install EPEL repo for CentOS
  yum: name=epel-release

- name: Install IM dependencies for CentOS
  yum: name=gcc,git,python-devel,libffi-devel,openssl-devel,python-pip,sqlite-devel,python-enum34,python-sqlite3dbm update_cache=yes
