- name: Install EPEL repo for CentOS
  yum: name=epel-release

- name: Yum install requisites RH 6/7/ Fedora 27-
  yum: name=python-pip,python-setuptools,sshpass,openssh-clients update_cache=yes
  when: (ansible_distribution_major_version|int >= 6 and ansible_distribution_major_version|int < 8) or (ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 28)

- name: Yum install requisites RH 8 / Fedora 28+
  command: yum install -y python2-pip python2-setuptools sshpass openssh-clients
  when: (ansible_distribution != "Fedora" and and ansible_distribution_major_version|int >= 8) or (ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 28)

- name: Yum install extra requisites RH 6
  yum: name=gcc,libffi-devel,openssl-devel,python-devel update_cache=yes
  when: ansible_distribution_major_version|int <= 6 
