- name: Install IM dependencies for CentOS
  yum: name=epel-release

- name: Install IM dependencies for CentOS
  yum: name=gcc,SOAPpy,python-devel,libffi-devel,openssl-devel,python-pip,sqlite-devel,python-sqlite3dbm,python-enum34 update_cache=yes
